 # Set to true to add reviewers to pull requests
   addReviewers: true

 # Set to true to add assignees to pull requests
   addAssignees: false

 # See the README for how to get usernames
 # A list of reviewers to be added to pull requests (GitHub user name)
   reviewers:
    - ccangialose
    - czantany1
    - em-gazelle
    - lawyu89
    - mattmcginnis
    - mstahl
    - hotfusionman
    - cachilders
    - scabaral
    - otheogar
    - sonoilconte

#   - dancernerd32
#   - ibratanov

 # A list of keywords to be skipped the process that add reviewers if pull requests include it
   skipKeywords:
   - WIP
   - RELEASE

 # A number of reviewers added to the pull request
 # Set 0 to add all the reviewers (default: 0)
   numberOfReviewers: 1
