 # Set to true to add reviewers to pull requests
   addReviewers: true

 # Set to true to add assignees to pull requests
   addAssignees: false

 # A list of reviewers to be added to pull requests (GitHub user name)
   reviewers:
    - ccangialose
    - christophermaujean
    - czantany1
    - dancernerd32
    - em-gazelle
    - ibratanov
    - jasonenglish
    - lawyu89
    - masimons
    - mattmcginnis
    - mstahl

 # A list of keywords to be skipped the process that add reviewers if pull requests include it
   skipKeywords:
   - WIP
   - RELEASE

 # A number of reviewers added to the pull request
 # Set 0 to add all the reviewers (default: 0)
   numberOfReviewers: 1
